[package]
name = "env_cfg_derive"
version = "0.2.0"
edition = "2024"
description = "Derive macros for env_config"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
heck = "0.5.0"
